spec:
  containers:
    - name: nginx

      volumeMounts:
        - name: game-storage
          mountPath: /data

  volumes:
    - name: game-storage

      persistentVolumeClaim:
        claimName: game-2048-pvc