apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: game-2048-hpa
  namespace: game-2048

  labels:
    app.kubernetes.io/name: game-2048
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/managed-by: kubectl

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 2048-deployment

  # Minimum pods always running
  minReplicas: 3

  # Maximum pods allowed during scaling
  maxReplicas: 10

  metrics:
    # CPU-based autoscaling
    - type: Resource

      resource:
        name: cpu

        target:
          type: Utilization

          # Target average CPU utilization across pods
          averageUtilization: 70

    # Memory-based autoscaling
    - type: Resource

      resource:
        name: memory

        target:
          type: Utilization

          # Target average memory utilization
          averageUtilization: 80

  behavior:
    scaleUp:
    #wait 60 sec to scale up
      stabilizationWindowSeconds: 60
    #HPA CAN SCALE 100% PODS WITH IN 60 SECONDS
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60

    scaleDown:
    #wait 100sec before scaling sown
      stabilizationWindowSeconds: 300
    #HPA CAN SCALE 50% PODS WITH IN 60 SECONDS
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60