apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-2048-pvc
  namespace: game-2048

  labels:
    app.kubernetes.io/name: game-2048
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: kubectl

spec:
  accessModes:
    - ReadWriteOnce #list, allowing only one node to do the action at a time
  
  resources:
    requests:
      storage: 1Gi #requesting 1gb of volume storage

  storageClassName: standard