apiVersion: v1
kind: Secret

metadata:
  name: game-2048-secret
  namespace: game-2048

  labels:
    app.kubernetes.io/name: game-2048
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:
  APP_SECRET_KEY: "change-me-production-secret"

  JWT_SECRET: "change-me-jwt-secret"

  API_TOKEN: "change-me-api-token"